### ISSUE TITLE
Invalid value. (offset: 0)

### ISSUE THREAD

**Issue by sinaabadi** [chesty/vroom-docker#1]
Hi
I run docker image and run following `curl` command that provided as sample for vroom-express project [in here](https://github.com/VROOM-Project/vroom-express#usage)
```
curl --header "Content-Type:application/json" --data '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}],"options":{"g":true}}' http://localhost:3000
```
it says: `{"code":1,"error":"Invalid value. (offset: 0)"}`

**Comment by chesty** [comment]
Hi sinaabadi, thanks for the report.

I worked out what triggers the issue and I've asked jcoupey, the author of vroom what's going on.
With the example curl command, vroom-express is executing the following

`vroom -a osrm-backend -p 5000 -m car -g '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}],"options":{"g":true}}'
`
which has the error, if I leave off the -m car parameter, it works OK.

`vroom -a osrm-backend -p 5000 -g '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}],"options":{"g":true}}'
`
I'll get back to you after jcoupey responds.

**Comment by chesty** [comment]
Hi sinaabadi,

if you change your docker-compose.yml to use `image: hammermc/vroom-docker:release-1.3.0` it will work. The latest vroom-express doesn't yet work with the latest vroom, the above change uses the last vroom release which does work.
